# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recommend',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
