# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0002_project_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='recommend',
        ),
        migrations.AddField(
            model_name='project',
            name='is_project',
            field=models.BooleanField(default=True),
        ),
    ]
