# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0002_auto_20161208_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
