# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 00:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0001_initial'),
        ('UniversitiesApp', '0004_auto_20161108_1557'),
        ('CompaniesApp', '0001_initial'),
        ('ProjectsApp', '0001_initial'),
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('companies', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompaniesApp.Company')),
                ('projects', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectsApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('courses', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.Course')),
                ('university', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GroupsApp.Group')),
                ('university', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University')),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
