# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 01:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_engineer',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_professor',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_student',
        ),
    ]
