# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 01:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0001_initial'),
        ('UniversitiesApp', '0004_auto_20161108_1557'),
        ('CompaniesApp', '0001_initial'),
        ('ProjectsApp', '0001_initial'),
        ('AuthenticationApp', '0002_auto_20161205_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('companies', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompaniesApp.Company')),
                ('projects', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectsApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('courses', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.Course')),
                ('university', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='contact_info',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_engineer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_professor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GroupsApp.Group'),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
    ]
