# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_auto_20161205_1617'),
        ('AuthenticationApp', '0002_auto_20161206_0304'),
    ]

    operations = [
    ]
