# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0003_merge_20161206_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
