# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0001_initial'),
        ('AuthenticationApp', '0003_auto_20161205_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='university',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='groups',
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(default=None, null=True, to='GroupsApp.Group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
    ]
