# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0004_auto_20161205_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='description',
        ),
    ]
