# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachser',
            new_name='Teacher',
        ),
    ]
