# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0003_auto_20161208_0159'),
        ('UniversitiesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.Professor'),
        ),
    ]
