# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_engineer_professor_student'),
        ('UniversitiesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('members', models.ManyToManyField(to='AuthenticationApp.Student')),
                ('professor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.Professor')),
            ],
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
    ]
