# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0002_auto_20161206_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
    ]
